#!/usr/bin/env bash


[[ -e dist ]] || mkdir dist
rm -f dist/*


dirs="sawtooth-core sawtooth-validator sawtooth-mktplace"
for d in $dirs; do
    pushd $d
    rm -rf dist
    python setup.py bdist_wheel
    cp dist/* ../dist/
    popd
done
    


