#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

REPOS="sawtooth-core sawtooth-validator sawtooth-mktplace"

for d in $REPOS; do
    pushd $d
    git checkout master 
    git pull
    popd
done
